name: Code Quality / Test Pipeline

on:
    push:
        branches:
            - 'renovate/*'
    pull_request:

jobs:
    pipeline:
        runs-on: ubuntu-latest
        if: (github.event_name == 'pull_request' && !contains(github.head_ref, 'renovate/')) || github.event_name == 'push' && contains(github.ref, 'renovate/')
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - run: |
                  echo 'hello world'
